# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelBuddy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='started_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='started', to='travelBuddy_app.user'),
            preserve_default=False,
        ),
    ]
